services:
  belkart_space_postgres_db:
    image: postgres:17
    environment:
      - POSTGRES_DB=belkart_space_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - app-network
  belkart_space_app:
    build: .
    environment:
      - CORS_ALLOWED_ORIGINS=https://hackatonbpc.netlify.app,http://localhost:9000
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/belkart_space_db
      - DB_USERNAME=username
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
